// Embeddings are generated by the Supabase Edge Function `embed`, which runs the
// gte-small model natively in the Supabase Edge Runtime and returns a 384-dim,
// mean-pooled, normalized vector. Doing this over the network keeps the Next.js
// app free of native ML dependencies (onnxruntime-node, sharp), so it deploys
// cleanly to serverless hosts like Vercel.

export const EMBEDDING_DIM = 384;

function embedTarget(): { url: string; key: string } {
  const base = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const key =
    process.env.SUPABASE_SERVICE_ROLE_KEY ||
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
  if (!base || !key) {
    throw new Error(
      "Supabase is not configured for embeddings. Set NEXT_PUBLIC_SUPABASE_URL and a Supabase key in the environment.",
    );
  }
  return { url: `${base}/functions/v1/embed`, key };
}

// Embed a single string into a 384-length unit vector.
export async function embed(text: string): Promise<number[]> {
  const { url, key } = embedTarget();
  let res: Response;
  try {
    res = await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        apikey: key,
        Authorization: `Bearer ${key}`,
      },
      body: JSON.stringify({ input: text }),
    });
  } catch {
    throw new Error("Could not reach the embedding service. Please try again.");
  }
  if (!res.ok) {
    const body = await res.text();
    throw new Error(
      `Embedding service error (${res.status}): ${body.slice(0, 200)}`,
    );
  }
  const data = await res.json();
  if (!Array.isArray(data.embedding)) {
    throw new Error("Embedding service returned no vector.");
  }
  return data.embedding as number[];
}

// Embed many strings (sequential calls to the edge function).
export async function embedBatch(texts: string[]): Promise<number[][]> {
  const vectors: number[][] = [];
  for (const t of texts) {
    vectors.push(await embed(t));
  }
  return vectors;
}
